<?php

/**
 * @file
 * Install, update and uninstall functions for the ln_hreflang module.
 */

/**
 * Implements hook_install().
 */
function ln_hreflang_install() {
}

/**
 * Implements hook_uninstall().
 */
function ln_hreflang_uninstall() {
   $langcodes = \Drupal::languageManager()->getLanguages();
   $langcodesList = array_keys($langcodes);
   foreach ($langcodesList as  $langcode) {
    \Drupal::state()->delete('ln_hreflang.hreflang.' . $langcode);
   }
}
