<?php

/**
 * @file
 * Main functions and hooks of context_advanced_datalayer module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function context_advanced_datalayer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Module help for the context_advanced_datalayer module.
    case 'help.page.context_advanced_datalayer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds integration advanced_datalayer and context module to manipulate GTM page variables.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_advanced_datalayer_alter().
 */
function context_advanced_datalayer_advanced_datalayer_alter(array &$tags, array $context) {

  /** @var \Drupal\context\ContextManager $contextManager */
  $contextManager = \Drupal::service('context.manager');

  foreach ($contextManager->getActiveReactions('context_advanced_datalayer') as $reaction) {

    $context_datalayer_data = array_filter($reaction->execute());

    // Unset the ID.
    unset($context_datalayer_data['id']);

    if (!empty($context_datalayer_data)) {
      foreach ($context_datalayer_data as $key => $value) {
        $tags[$key] = $value;
      }
    }
  }

}
