<?php

use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function ln_c_buy_now_component_field_widget_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  $field_definition = $context['items']->getFieldDefinition();
  $paragraph_entity_reference_field_name = $field_definition->getName();

  // Reference field in the content type component.
  if ($paragraph_entity_reference_field_name == 'field_components') {
    /** @see \Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget::formElement() */
    $widget_state = WidgetBase::getWidgetState($element['#field_parents'], $paragraph_entity_reference_field_name, $form_state);

    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph_instance = $widget_state['paragraphs'][$element['#delta']]['entity'];
    $paragraph_type = $paragraph_instance->bundle();

    // Determine which paragraph type is being embedded.
    if ($paragraph_type == 'ln_c_buy_now_component') {
      $dependee_field_name = 'field_ln_c_type_buy_now';
      $selector = sprintf('select[name="%s[%d][subform][%s]"]', $paragraph_entity_reference_field_name, $element['#delta'], $dependee_field_name);

      // Dependent fields for adimo buy now.
      $element['subform']['field_ln_c_adimo_buy_now']['#states'] = [
        'visible' => [
          $selector => ['value' => 'adimo'],
        ],
      ];

      // Dependent fields for price spider buy now.
      $element['subform']['field_ln_c_price_spider_buy_now']['#states'] = [
        'visible' => [
          $selector => ['value' => 'price_spider'],
        ],
      ];

      // Dependent fields for wunderman buy now.
      $element['subform']['field_ln_c_wunderman_buy_now']['#states'] = [
        'visible' => [
          $selector => ['value' => 'wunderman'],
        ],
      ];
    }
  }
}

/**
 * Implements hook_preprocess_theme().
 */
function ln_c_buy_now_component_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ln_c_buy_now_component' => [
      'template' => 'paragraph--ln-c-buy-now-component',
      'base hook' => 'paragraphs',
    ],
  ];
}