<?php

/**
 * @file
 * Contains dsu_c_image.module.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_image_preprocess_paragraph(&$variables) {
  // Load the css file when the rendered element is a Image Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_image/general';
}

/**
 * Implements hook_theme.
 */
function dsu_c_image_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_image' => [
      'template' => 'paragraph--c-image',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_image_ln_sample_content() {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
    $module_handler = \Drupal::service('module_handler');
    /** @var \Drupal\Core\Extension\Extension $module_object */
    $module_object = $module_handler->getModule(basename(__FILE__, '.module'));
    $module_name = $module_object->getName();

    $source = drupal_get_path('module', $module_name) . '/content';
    /** @var \Drupal\Core\File\FileSystemInterface $file_system */
    $file_system = \Drupal::service('file_system');
    $files = $file_system->scanDirectory($source, '/demo.*\.(yml)$/');
    $yaml_file_path = NULL;
    foreach ($files as $file) {
        $yaml_file_path[] = '/content/' . $file->filename;
    }

    return $yaml_file_path;
}