<?php

/**
 * @file
 * Contains dsu_c_view.module file.
 */


/**
 * Implements hook_theme().
 */
function dsu_c_view_theme($existing, $type, $theme, $path) {
  return [
    'exposed-extras' => [
      'template'  => 'exposed-extras',
      'variables' => [
        'clear_link'    => NULL,
        'clear_text'    => NULL,
        'searched_text' => NULL,
        'search_result' => NULL,
      ],
    ],
	'paragraph__dsu_c_view' => [
      'template' => 'paragraph--dsu-c-view',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dsu_c_view_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  if ($paragraph->bundle() == 'dsu_c_view') {
    // Hide title if show title is checked.
    if (!$paragraph->field_show_title->value) {
      unset($variables['content']['field_title']);
    }
  }
}
