<?php

/**
 * Implements hook_preprocess_image().
 */
function ln_lazy_load_image_preprocess_image(&$vars) {
  //Get the url of the request and remove form drupal admin section.
  $current_uri = \Drupal::request()->getRequestUri();
  $url_array = explode('?', $current_uri);

  if (!preg_match('/(^\/admin\/|\/(node|media)\/[a-zA-Z0-9]+\/edit|\/(node|media)\/add\/|^\/entity-embed\/)/', $url_array[0])) {
    // Adds lazyload class to all images and changes src to data-src.
    if (isset($vars['attributes']['src']) && !empty($vars['attributes']['src'])) {
      $vars['#attached']['library'][] = 'ln_lazy_load_image/lazy_load_image';
      $vars['attributes']['class'][] = 'lazyload';
      $vars['attributes']['data-src'] = $vars['attributes']['src'];
      unset($vars['attributes']['src']);
    }
  }
}

/**
 * Implements hook_preprocess_responsive_image().
 */
function ln_lazy_load_image_preprocess_responsive_image(&$vars) {
  // Changes srcset to data-srcset.
  if (array_key_exists('sources', $vars)) {
    foreach ($vars['sources'] as $key => $data) {
      $vars['sources'][$key]['data-srcset'] = $data['srcset'];
      $vars['sources'][$key]['srcset'] = '';
    }
  }
}