<?php

use Drupal\bootstrap\Bootstrap;
use Drupal\bootstrap\Utility\Element;

/**
 * Implements HOOK_preprocess_theme().
 */
function dsu_c_link_document_container_theme($existing, $type, $theme, $path) {
    return [
    'paragraph__c_link_document_container' => [
      'template' => 'paragraph--c-link-document-container',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_link' => [
      'template' => 'paragraph--c-link',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_document' => [
      'template' => 'paragraph--c-document',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_link_document_container_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'c_document' || $variables['paragraph']->getType() == 'c_link') {
    $variables['#attached']['library'][] = 'dsu_c_link_document_container/link-container';
  }
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_link_document_container_ln_sample_content() {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
    $module_handler = \Drupal::service('module_handler');
    /** @var \Drupal\Core\Extension\Extension $module_object */
    $module_object = $module_handler->getModule(basename(__FILE__, '.module'));
    $module_name = $module_object->getName();

    $source = drupal_get_path('module', $module_name) . '/content';
    /** @var \Drupal\Core\File\FileSystemInterface $file_system */
    $file_system = \Drupal::service('file_system');
    $files = $file_system->scanDirectory($source, '/demo.*\.(yml)$/');
    $yaml_file_path = NULL;
    foreach ($files as $file) {
        $yaml_file_path[] = '/content/' . $file->filename;
    }

    return $yaml_file_path;
}