<?php

/**
 * @file
 * The Maintenance200 module sets a non-503 HTTP response in maintenance mode.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function maintenance200_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.maintenance200':
      return t('
        <h2>Maintenance200 module.</h2>
        <h3>Instructions</h3>
        <p>Install the module as normal and enable in <strong>/admin/modules</strong>.</p>
        <p>On the module configuration form you will find a switch to turn on or off the rewriting of the HTTP code returned when the site is in maintenance mode, as well as a field where you
        can input the numeric HTTP which the site should return.</p>
      ');
  }
}
