field.formatter.settings.field_timer_simple_text:
  type: field.formatter.settings.datetime_time_ago
  label: 'Field Timer Text timer or countdown formatter display settings'
  mapping:
    type:
      type: string
      label: 'Type'

field.formatter.settings.field_timer_county:
  type: mapping
  label: 'Field Timer County formatter display settings'
  mapping:
    animaton:
      type: string
      label: 'Animation'
    speed:
      type: integer
      label: 'Speed'
    theme:
      type: string
      label: 'Theme'
    background:
      type: string
      label: 'Background'
    reflection:
      type: boolean
      label: 'Add reflection'
    reflectionOpacity:
      type: float
      label: 'Reflection opacity'

field.formatter.settings.field_timer_countdown_base:
  type: mapping
  mapping:
    type:
      type: string
      label: 'Type'

field.formatter.settings.field_timer_countdown:
  type: field.formatter.settings.field_timer_countdown_base
  label: 'Field Timer jQuery Countdown formatter display settings'
  mapping:
    use_system_language:
      type: boolean
      label: 'Use system language'
    regional:
      type: string
      label: 'Region'
      translatable: true
    format:
      type: string
      label: 'Format'
    layout:
      type: string
      label: 'Layout'
    compact:
      type: boolean
      label: 'Display in compact format'
    significant:
      type: integer
      label: 'Granularity'
    timeSeparator:
      type: string
      label: 'Time separator'
    padZeroes:
      type: boolean
      label: 'Pad with zeroes'

field.formatter.settings.field_timer_countdown_led:
  type: field.formatter.settings.field_timer_countdown_base
  label: 'Field Timer jQuery Countdown LED formatter display settings'
  mapping:
    countdown_theme:
      type: string
      label: 'Theme'
    max_count_of_days:
      type: integer
      label: 'Max count of days'
    display_days:
      type: boolean
      label: 'Display days'
    display_hours:
      type: boolean
      label: 'Display hours'
    display_minutes:
      type: boolean
      label: 'Display minutes'
    display_seconds:
      type: boolean
      label: 'Display seconds'
