<?php

/**
 * @file
 * Contains indegenecustom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function indegenecustom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the indegenecustom module.
    case 'help.page.indegenecustom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This dispaly information what you enter your application.') . '</p>';
      return $output;

    default:
  }
}

function indegenecustom_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $form['#attached']['library'][] = "indegenecustom/attach-library";
}

/**
 * Implements hook_theme().
 */
function indegenecustom_theme($existing, $type, $theme, $path) {
  return [
    'clock_template' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}