<?php

/**
 * @file
 * Contains ln_contenthub.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

  /**
 * Implements hook_help().
 */
function ln_contenthub_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ln_contenthub':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add images easily from Content Hub') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ln_contenthub_theme() {
  return [
    'ln_contenthub' => [
      'template' => 'ln_contenthub-search-result',
      'variables' => [
        'src' => NULL,
        'title' => NULL,
      ],
    ]
  ];
}

/**
 * Implements hook_cron().
 */
function ln_contenthub_cron() {
  $delete_expired_images = \Drupal::config('ln_contenthub.settings')->get('ln_contenthub_delete_expired');
  $query = \Drupal::entityQuery('media');
  $entity_ids = $query->execute();

  foreach ($entity_ids as $entity_id) {
    $media = Media::load($entity_id);
    $media_status = $media->get('status')->getString();
    if(in_array($media->bundle(), ['content_hub', 'content_hub_document', 'content_hub_video'])) {
      $expiration_date = isset($media->get('field_media_ln_contenthub_ipr_ex')->getValue()[0]['value']) ? $media->get('field_media_ln_contenthub_ipr_ex')->getValue()[0]['value'] : FALSE;
      if($delete_expired_images == 'delete_assets' && $expiration_date && strtotime($expiration_date) <= time()) {
        try{
          $field_name = (($media->bundle() == 'content_hub') ? 'field_media_ln_contenthub_image' : (($media->bundle() == 'content_hub_document') ? 'field_media_ln_contenthub_docume' : (($media->bundle() == 'content_hub_video') ? 'field_media_ln_contenthub_video' :'')));
          $file = \Drupal\file\Entity\File::load($media->get($field_name)->target_id);
          $media->delete();
          $file->delete();
          \Drupal::logger('ln_contenthub')->alert('Deleted entity @entity due to expired Intellectual Property Rights.', ['@entity' => $entity_id]);
        }catch (\Exception $e) {
          \Drupal::logger('ln_contenthub')->error('Error deleting entity %entity : %error.', array('%entity' => $entity_id, '%error' => $e->getMessage()));
        }
      }
      if($delete_expired_images == 'disable_assets' && $expiration_date && strtotime($expiration_date) <= time() && $media_status ) {
        try{
          $media->set('status',false);
          $media->save();
          \Drupal::logger('ln_contenthub')->alert('Disabled entity @entity due to expired Intellectual Property Rights.', ['@entity' => $entity_id]);
        }catch (\Exception $e) {
          \Drupal::logger('ln_contenthub')->error('Error deleting entity %entity : %error.', array('%entity' => $entity_id, '%error' => $e->getMessage()));
        }
      }
    }
  }

  // Contenthub Cron queue jobs.
  $config = Drupal::service('config.factory')->getEditable('ln_contenthub.settings');
  $interval = $config->get('ln_contenthub_media_sync_interval');
  $last_run = Drupal::state()->get('ln_contenthub.next_execution', time() - $interval - 1);
  if ($last_run <= time() - $interval) {
    $queue = Drupal::queue('syncronizer_contenthub_media_queue');
    Drupal::logger('ContenthubLogger')->notice('Job created');
    $item = 1;
    $queue->createItem($item);
    Drupal::state()->set('ln_contenthub.next_execution', time() + $interval);
  }
}
/**
 * Implements hook_views_query_alter().
 */
function ln_contenthub_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'expiry_media' && $view->getDisplay()->display['id'] == 'page_1') {
    if (isset($query->where[1]['conditions'][2]) &&
      $query->where[1]['conditions'][2]["field"] == 'media__field_media_ln_contenthub_ipr_ex.field_media_ln_contenthub_ipr_ex_value' ) {
      $query->where[1]['conditions'][2]["value"] = date('Y-m-d', strtotime('+2 months'));
      $query->where[1]['conditions'][2]["operator"] = '<=' ;
    }
    if (isset($query->where[1]['conditions'][3]) &&
      $query->where[1]['conditions'][3]["field"] == 'media__field_media_ln_contenthub_ipr_ex.field_media_ln_contenthub_ipr_ex_value' ) {
      $query->where[1]['conditions'][3]["value"] = date('Y-m-d');
      $query->where[1]['conditions'][3]["operator"] = '>=' ;
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ln_contenthub_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'expiry_media' && $view->getDisplay()->display['id'] == 'page_1') {
    foreach($view->result as $value){
      $mediaType = $value->_entity->get('bundle')->getString();
      $mediaId = $value->_entity->get('mid')->getString();
      $media = Media::load($mediaId);
      $field_name = (($mediaType == 'content_hub') ? 'field_media_ln_contenthub_image' : (($mediaType == 'content_hub_document') ? 'field_media_ln_contenthub_docume' : (($mediaType == 'content_hub_video') ? 'field_media_ln_contenthub_video' :'')));
      $fid = $media->$field_name->target_id;
      $value->_entity->set('field_media_ln_contenthub_name', $fid);
    }
  }
}
