<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_help().
 */
function google_optimize_js_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.google_optimize_js') {
    return new TranslatableMarkup('
Google Optimize is a free website optimization tool that helps increase
conversion rates by continually testing different combinations of website
content.  It requires a Google Optimize account which can be created on the
<a href="@google_optimize_url">Google Optimize site</a>.
', ['@google_optimize_url' => 'https://optimize.google.com']);

  }
}

/**
 * Implements hook_page_attachments().
 */
function google_optimize_js_page_attachments(array &$attachments) {

  $config = Drupal::config('google_optimize_js.settings');

  // Add the google optimize configuration cache tags in all cases.
  $attachments['#cache']['tags'] = Cache::mergeTags(
    $attachments['#cache']['tags'] ?? [],
    $config->getCacheTags()
  );

  $container = $config->get('container');

  // Ensure the container ID does not contain invalid characters.
  if (empty($container) || !preg_match('/^(GTM|OPT)-[a-zA-Z0-9]{7}$/', $container)) {
    return;
  }

  $base_weight = $config->get('datalayer_js_weight');
  $anti_flicker_timeout = $config->get('anti_flicker_timeout');

  // Ensure the base weight and timeout values are numbers.
  if (!is_numeric($base_weight) || !is_numeric($anti_flicker_timeout)) {
    return;
  }
  /* @var $inclusion \Drupal\google_optimize_js\InclusionInterface */
  $inclusion = Drupal::service('google_optimize_js.inclusion');

  if ($inclusion->includeOptimizeSnippet()) {
    // Place the optimize script closely after datalayer initialization.
    $optimize_script = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => [
          'src' => 'https://www.googleoptimize.com/optimize.js?id=' . $container,
        ],
        '#weight' => $base_weight + 0.1,
      ],
      'google_optimize',
    ];

    if ($inclusion->includeAntiFlickerSnippet()) {

      // If the anti-flicker script is used, add a safety net.
      // If the optimize script can't be loaded, immediately show the page.
      $optimize_script[0]['#attributes']['onerror'] = 'if (window.dataLayer.hide.end) { window.dataLayer.hide.end(); }';

      // The anti-flicker CSS should go very high in the head.
      $anti_flicker_css = [
        '#type' => 'html_tag',
        '#tag' => 'style',
        '#value' => '.async-hide { opacity: 0 !important }',
        '#weight' => $base_weight - 0.1,
      ];
      $attachments['#attached']['html_head'][] = [$anti_flicker_css, 'google_optimize_anti_flicker_css'];

      // The anti-flicker JS should go between the datalayer initialization and
      // the optimize library.
      $anti_flicker_js = [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => sprintf(
          "(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
  h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
  (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
  })(window,document.documentElement,'async-hide','dataLayer',%d,
  {'%s':true});",
          $anti_flicker_timeout,
          $container
        ),
        '#weight' => $base_weight + 0.05,
      ];

      $attachments['#attached']['html_head'][] = [$anti_flicker_js, 'google_optimize_anti_flicker_js'];
    }
    $attachments['#attached']['html_head'][] = $optimize_script;
  }
}
