<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\ln_quiz\LnQuizConstants;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function ln_quiz_paragraph_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if($entity->bundle() == 'quiz'){
    $build['#attributes']['data-quiz-id'] = $entity->id();
    $build['#attached']['library'][] = 'ln_quiz/quiz-main';
    $build['#attached']['drupalSettings'] = [
      'ln_quiz' => [
        $entity->id() => [
          'urls' => [
            'init' => Url::fromRoute('ln_quiz.process', [
              'quiz' => $entity->id(),
              'action' => LnQuizConstants::QUIZ_ACTION_INIT
            ])->toString()
          ]
        ]
      ]
    ];
  }
}
