<?php

namespace Drupal\ln_c_hotspot_areas\Plugin\Field\FieldFormatter;

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\image\Plugin\Field\FieldFormatter\ImageFormatter;
use Drupal\ln_c_hotspot_areas\Entity\HotspotArea;

/**
 * Plugin implementation of the 'image_image' formatter.
 *
 * @FieldFormatter(
 *   id = "hotspot_areas_formatter",
 *   label = @Translation("Hotspots areas formatter"),
 *   field_types = {
 *     "image"
 *   }
 * )
 */
class HotspotAreasFormatter extends ImageFormatter {

  /**
   * @inheritdoc
   */
  public function settingsForm(array $form, FormStateInterface $form_state) {
    return parent::settingsForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public function viewElements(FieldItemListInterface $items, $langcode) {

    $elements = parent::viewElements($items, $langcode);

    $image_style = !empty($this->getSetting('image_style')) ? $this->getSetting('image_style') : 'none';
    $field_name = $items->getName();
    $entity_id = $items->getEntity()->id();

    $files = $this->getEntitiesToView($items, $langcode);

    $info = [
      'field_name' => $field_name,
      'image_style' => $image_style,
      'entity_id' => $entity_id,
      'lang' => $langcode,
    ];

    /** @var \Drupal\file\FileInterface $file */
    foreach ($files as $delta => $file) {
      $info['fid'] = $file->id();
      $hotspots = HotspotArea::loadByTarget($info);

      $editable = FALSE;
      // Load library for edit hotspots if user in permission & is not backoffice, because it provoke conflicts with paragraphs preview
      if ($this->currentUser->hasPermission('edit hotspot area') && ! \Drupal::service('router.admin_context')->isAdminRoute()) {
        $editable = TRUE;
        $elements[$delta]['#attached']['library'][] = 'ln_c_hotspot_areas/edit';
      }

      // Attach hotspots data to js settings.
      /** @var \Drupal\ln_c_hotspot_areas\HotspotAreaInterface $hotspot */
      $hotspots_to_show = [];
      foreach ($hotspots as $hid => $hotspot) {
        $title = $hotspot->getTitle();
        $description = $hotspot->getDescription();
        $format = $hotspot->getDescriptionFormat();
        $link = $hotspot->getLink();
        $link_title = $hotspot->getLinkTitle();
        $shape = $hotspot->getShape();
        $mouse_behaviour = $hotspot->getMouseBehaviour();
        $value = [
          'title' => $title,
          'description' => check_markup($description, $format),
          'link' => !is_null($link) ? $link : '',
          'link_title' => !is_null($link_title) ? $link_title : '',
          'shape' => $shape,
          'mouse_behaviour' => $mouse_behaviour
        ];
        foreach ($hotspot->getCoordinates() as $coordinate => $val) {
          $value[$coordinate] = $val;
        }
        $hotspots_to_show[$hid] = $value;
      }

      // Add cache tag 'hotspots:field_name:fid:image_style'.
      $elements[$delta]['#cache']['tags'][] = 'hotspot areas:' . $info['entity_id'] . ':' . $info['lang'] . ':' . $info['field_name'] . ':' . $info['fid'] . ':' . $info['image_style'];
      // Attach libraries.
      $elements[$delta]['#attached']['drupalSettings']['hotspot_areas'][$entity_id][$langcode][$field_name][$file->id()][$image_style]['hotspots'] = $hotspots_to_show;
      $elements[$delta]['#attached']['library'][] = 'ln_c_hotspot_areas/view';
      // Change element theme from 'image_formatter'.
      $elements[$delta]['#theme'] = 'hotspot_areas_formatter';
      // Add additional info for render.
      $elements[$delta]['#info'] = $info;
      $elements[$delta]['#info']['editable'] = $editable;

      $form = \Drupal::formBuilder()->getForm('Drupal\ln_c_hotspot_areas\Form\HotspotAreasForm');
      $elements[$delta]['#form'] = $form;
    }

    return $elements;
  }

}
