<?php

/**
 * @file
 * Contains dsu_c_map.module.
 */

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_map_preprocess_paragraph(&$variables) {
  // Load the css file when the rendered element is a Map.
  $variables['#attached']['library'][] = 'dsu_c_map/general';
}

/**
 * Implements HOOK_theme().
 */
function dsu_c_map_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_map' => [
      'template' => 'paragraph--c-map',
      'base hook' => 'paragraphs',
    ],
  ];
}

