<?php

/**
 * @file
 * Contains layout_builder_kit.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function layout_builder_kit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the layout_builder_kit module.
    case 'help.page.layout_builder_kit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains several components useful when building pages in Layout Builder.') . '</p>';
      $output .= '<p>' . t('See the documentation at <a href="https://performantlabs.com/layout-builder-kit/layout-builder-kit">here</a>.') . '</p>';
      return $output;

    default:
  }
}
