maintenance200.settings:
  type: config_object
  label: 'Maintenance 200 settings'
  mapping:
    maintenance200_enabled:
      type: integer
      label: 'Enable custom status code during maintenance mode'
    maintenance200_status_code:
      type: integer
      label: 'Status code to return during maintenance mode'
