<?php

/**
 * Implements hook_theme().
 */
function indegene_common_theme($existing, $type, $theme, $path) {

  $items = ['name' => 'shamsher', 'company' => 'indegene'];
  return [
    'indegene_custom_block' =>                  // this is the name of the template
      [
        'variables' => ['data' => $items],
      ],
  ];
}


/**
 * Implements hook_mail().
 */
function indegene_common_mail($key, &$message, $params) {
  switch ($key) {
    case 'forward_email':
      $message['from'] = 'test@site.com';
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
