<?php

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme().
 */
function indegene_common_theme($existing, $type, $theme, $path) {

  $items = ['name' => 'shamsher', 'company' => 'indegene'];
  return [
    'indegene_custom_block' =>                  // this is the name of the template
      [
        'variables' => ['data' => $items],
      ],
  ];
}


/**
 * Implements hook_mail().
 */
function indegene_common_mail($key, &$message, $params) {
  switch ($key) {
    case 'forward_email':
      $message['from'] = 'test@site.com';
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}


/**
 * Implements hook_form_alter().
 */
function indegene_common_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {


  if ($form_id == 'comment_comment_form') {



    $form['indegene_amazon_seceret_id'] = [
      '#type' => 'textfield',
      '#title' => t('Indegene seceret id'),
      '#descriptions' => 'this is secret id',
      '#required' => TRUE,
    ];

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'mymodule_form_submit';
      }
    }
  }


}

