<?php

use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function dsu_engage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dsu_engage':
      $output = '<h2>' . t('DSU Engage') . '</h2>';
      $output .= '<p>' . t('Provide a "Contact us" form connected with Engage') . '<p>';
      $output .= '<p>' . t('If you are installing this module in Drupal 8.4.x, you should install the follow core patch:') . '</p>';
      $output .= '<p>' . Link::fromTextAndUrl(t('1091852_70-8.4.x - Display Bug when using #states (Forms API) with Ajax Request'), Url::fromUri('https://www.drupal.org/files/issues/1091852_70-8.4.x.patch', array()))
          ->toString() . '<p>';
      $output .= '<p>' . t('If you are installing this module in Drupal 8.5.x, you should install the follow core patch:') . '</p>';
      $output .= '<p>' . Link::fromTextAndUrl(t('1091852_70 - Display Bug when using #states (Forms API) with Ajax Request'), Url::fromUri('https://www.drupal.org/files/issues/1091852_70.patch', array()))
          ->toString() . '<p>';
      $output .= '<p>' . t('If you are installing this module in Drupal 8.7.x, you should install the follow core patch:') . '</p>';
      $output .= '<p>' . Link::fromTextAndUrl(t('1091852_77 - Display Bug when using #states (Forms API) with Ajax Request'), Url::fromUri('https://www.drupal.org/files/issues/2018-08-22/1091852-77.patch', array()))
          ->toString() . '<p>';

      return $output;
  }
}

/**
 * Implements hook_theme_registry_alter
 */
function dsu_engage_theme($existing, $type, $theme, $path) {
  return [
    'dsu_engage_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * [get_file_url_using_fid description]
 *
 * @param  [type] $fid [description]
 *
 * @return [type]      [description]
 */
function get_engage_file_url_using_fid($fid) {
  $file_url = '';
  if (!empty($fid)) {
    $file_arr = File::load($fid);
    if (!empty($file_arr)) {
      $file_url = file_create_url($file_arr->get('uri')->value);
    }
  }

  return $file_url;
}
