# Schema for the configuration files of No Referrer module.

noreferrer.settings:
  type: config_object
  label: 'No Referrer settings'
  mapping:
    noopener:
      type: boolean
      label: 'Add rel="noopener" link type if link has a target'
    noreferrer:
      type: boolean
      label: 'Add rel="noreferrer" link type to non-whitelisted links'
    publish:
      type: boolean
      label: 'Publish list of whitelisted domains'
    subscribe_url:
      type: string
      label: 'Subscribe to external list of whitelisted domains'
    whitelisted_domains:
      type: string
      label: 'Whitelisted domains'
