<?php

/**
 * @file
 * Module file for views_infinite_scroll.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;
use Drupal\views_infinite_scroll\Plugin\views\pager\InfiniteScroll;

/**
 * Implements hook_preprocess_views_infinite_scroll_pager().
 */
function views_infinite_scroll_preprocess_views_infinite_scroll_pager(&$vars) {
  // The important parts we needed lifted wholesale from
  // template_preprocess_views_mini_pager().
  /** @var \Drupal\Core\Pager\PagerManagerInterface $pager_manager */
  $pager_manager = \Drupal::service('pager.manager');
  $element = $vars['element'];
  $parameters = $vars['parameters'];
  $pager = $pager_manager->getPager($element);

  if (isset($pager) && $pager->getCurrentPage() < ($pager->getTotalPages() - 1)) {
    $options = [
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager->getCurrentPage() + 1),
    ];
    $vars['items']['next']['href'] = Url::fromRoute('<none>', [], $options);
  }
  $vars['#cache']['contexts'][] = 'url.query_args';
  $vars['attributes'] = new Attribute([
    'class' => ['js-pager__items', 'pager'],
    'data-drupal-views-infinite-scroll-pager' => $vars['options']['automatically_load_content'] ? 'automatic' : TRUE,
  ]);

}

/**
 * Implements hook_preprocess_views_view().
 */
function views_infinite_scroll_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->getDisplay()->isPagerEnabled() && !empty($vars['rows'])) {
    $pager = $view->getPager();
    if ($pager && $pager instanceof InfiniteScroll) {
      if ($view->getDisplay()->getPluginId() == 'page') {
        $current = $pager->getCurrentPage();
        $attachments = &drupal_static(__FUNCTION__);
        if ($current) {
          $element = \Drupal::service('pager.manager')
            ->getUpdatedParameters([], $pager->getPagerId(), $current - 1);
          if ($current - 1 === 0) {
            unset($element['page']);
          }
          $attachments['prev'] = Url::fromRoute('<current>', $element)
            ->toString();
        }
        if ($current < ($pager->getPagerTotal() - 1)) {
          $element = \Drupal::service('pager.manager')
            ->getUpdatedParameters([], $pager->getPagerId(), $current + 1);
          $attachments['next'] = Url::fromRoute('<current>', $element)
            ->toString();
        }
      }
      if (!isset($vars['rows']['#theme_wrappers'])) {
        $vars['rows']['#theme_wrappers'] = [];
      }
      $vars['rows']['#theme_wrappers']['container']['#attributes']['data-drupal-views-infinite-scroll-content-wrapper'] = TRUE;
      $vars['rows']['#theme_wrappers']['container']['#attributes']['class'][] = 'views-infinite-scroll-content-wrapper';
      $vars['rows']['#theme_wrappers']['container']['#attributes']['class'][] = 'clearfix';
    }
  }
}

/**
 * Implements hook_page_attachments().
 */
function views_infinite_scroll_page_attachments(array &$attachments) {
  if ($tags = drupal_static('views_infinite_scroll_preprocess_views_view')) {
    foreach ($tags as $name => $url) {
      $attachments['#attached']['html_head'][] = [
        [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => $name,
            'href' => $url,
          ],
        ],
        'pager_link_' . $name,
      ];
    }
  }
}
