<?php

/**
 * Implements HOOK_preprocess_theme().
 */
function ln_shopify_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_shopify' => [
      'template' => 'paragraph--c-shopify',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function ln_shopify_preprocess_paragraph(&$variables) {
  // Load the css file when the rendered element is a Shopify Paragraph.
  if ($variables['paragraph']->getType() == 'c_shopify') {
    $variables['#attached']['library'][] = 'ln_shopify/general';
  }
}