<?php

  /**
   * @file
   * Contains tint.module.
   */

  use Drupal\Core\Routing\RouteMatchInterface;

  /**
   * Implements hook_help().
   */
  function ln_tint_connector_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      // Main module help for the tint module.
      case 'help.page.ln_tint_connector':
        $output = '';
        $output .= '<h3>' . t( 'About' ) . '</h3>';
        $output .= '<p>' . t( 'Integration with the TINT social feed platform.' ) . '</p>';

        return $output;

      default:
    }
  }

  /**
   * Implements hook_theme().
   */
  function ln_tint_connector_theme($existing, $type, $theme, $path) {
    return [
      'paragraph__dsu_tint' => [
        'template' => 'paragraph--dsu-tint',
        'base hook' => 'node',
      ],
    ];
  }

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function ln_tint_connector_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'dsu_tint') {
    // Attach library for dsu_tint
    $variables['#attached']['library'][] = 'ln_tint_connector/tint_event_tracking';
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    // Fetch the title of the current node.
    $variables['titlefordataLayer'] = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
  }
}