<?php

/**
 * @file
 * A module that adds testimonial functionality.
 */

/**
 * Implements hook_preprocess_theme().
 */
function ln_c_testimonial_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_testimonial_item' => [
      'template'  => 'paragraph--c-testimonial-item',
      'base hook' => 'paragraphs',
    ],
    'paragraph__c_testimonial'      => [
      'template'  => 'paragraph--c-testimonial',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function ln_c_testimonial_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'c_testimonial') {
    $variables['#attached']['library'][] = 'ln_c_testimonial/testimonial';
  }
  if ($variables['paragraph']->getType() == 'c_testimonial_item') {
    $variables['#attached']['library'][] = 'ln_c_testimonial/testimonial-item';
  }
}

/**
 * Implements hook_ln_sample_content().
 */
function ln_c_testimonial_ln_sample_content() {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::service('module_handler');
  /** @var \Drupal\Core\Extension\Extension $module_object */
  $module_object = $module_handler->getModule(basename(__FILE__, '.module'));
  $module_name = $module_object->getName();

  $source = drupal_get_path('module', $module_name) . '/content';
  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  $files = $file_system->scanDirectory($source, '/demo.*\.(yml)$/');
  $yaml_file_path = NULL;
  foreach ($files as $file) {
    $yaml_file_path[] = '/content/' . $file->filename;
  }

  return $yaml_file_path;
}
