# Schema for the configuration files of the ACSF Connector module.

acsf.settings:
  type: config_object
  label: 'Acquia Cloud Site Factory settings'
  mapping:
    maintenance_time:
      type: integer
      label: 'Time needed for the maintenance'
    site_owner_maintenance_mode:
      type: boolean
      label: 'Maintenance mode'
    local_user_accounts:
      type: boolean
      label: 'Allow local logins'
