features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://Indegene Logo_Final-01-web (1)_0.png'
favicon:
  use_default: 1
