<?php

namespace Drupal\ln_datalayer\Plugin\AdvancedDatalayer\Tag;

use Drupal\advanced_datalayer\Plugin\AdvancedDatalayer\Tag\DatalayerDynamicNameBase;

/**
 * The basic "gaClientID" datalayer tag.
 *
 * @AdvancedDatalayerTag(
 *   id = "gaClientID",
 *   label = @Translation("GA client ID"),
 *   description = @Translation("This  parameter  should  contain  the  User's  GA  Client  ID.    This  is automatically generated by Google Analytics and stored  in a cookie on the user's system"),
 *   group = "userInformation",
 *   global = TRUE,
 *   required = FALSE,
 *   translatable = FALSE,
 *   show_empty = TRUE,
 *   weight = 4,
 * )
 */
class GaClientID extends DatalayerDynamicNameBase {
  // Nothing here yet. Just a placeholder class for a plugin
  // GA will be calculated on JS side.
}
