<?php

/**
 * @file
 * Contains ln_contactus_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\dsu_engage\Controller\DsuEngageController;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_preprocess_theme().
 *
 * Create template for contactus webform.
 */
function ln_contactus_block_theme($existing, $type, $theme, $path) {
  return [
    'webform__contact_us' => [
      'base hook' => 'webform',
    ],
  ];
}

/**
 * Implements hook_help().
 *
 * Main module help for the ln_contactus_block module.
 */
function ln_contactus_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ln_contactus_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Contact-us webform as a block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add submit handler on contactus webform.
 */
function ln_contactus_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strstr($form_id, 'webform_submission_contact_us_')) {
	$form['#attached']['library'][] = 'ln_contactus_block/contactus-styling';  
    $form['actions']['submit']['#submit'] = array_merge(
      ['_ln_contactus_block_submit_handler'],
      $form['actions']['submit']['#submit']
    );
    // Set DSU Engage configuration.
    $config = \Drupal::service('config.factory')->getEditable('dsu_engage.settings');
	$send = 0;
	
	// Send contact us webform data in engage based on configuration.
    if (!empty($config->get('dsu_engage_api_send_to_engage'))) {
      $send = $config->get('dsu_engage_api_send_to_engage');
    }
    $form['elements']['send_to_engage']['#default_value'] = $send;
    $countryList = $config->get('dsu_engage_api_country_select');
	// Create option values for country.
    if (!empty($countryList)) {
      $country_options = $form["elements"]["form_wrapper"]["country"]["#options"];
      foreach ($country_options as $key => $value) {
        if (!in_array($key, $countryList)) {
          unset($country_options[$key]);
        }
      }
      $form["elements"]["form_wrapper"]["country"]["#options"] = $country_options;
    }
    $business_email = $config->get('dsu_engage_api_business_email');
    if (!empty($business_email)) {
      $form['elements']['business_email']['#default_value'] = $business_email;
    }
  }
}

/**
 * Custom submit handler for integration with Engage API.
 */
function _ln_contactus_block_submit_handler(&$form, FormStateInterface &$form_state) {
  // Check if send_to_engage is True.
  $send_to_engage = $form_state->getValue('send_to_engage');
  $store_locally = 0;
  if ($send_to_engage == 0) {
    $store_locally = 1;
  }
  else {
    // Check if selected country is in exclusion list.
    $config = \Drupal::service('config.factory')->getEditable('dsu_engage.settings');
    $exclusion_list = $config->get('dsu_engage_api_exclusion_list');
    $location = $form_state->getValue('country');
    if (in_array($location, $exclusion_list)) {
      $store_locally = 1;
      $form_state->setValue('send_to_engage', 0);
    }
  }

  // Check is webform to be stored locally.
  if ($store_locally == 1) {
    return;
  }
  else {
    foreach ($form['actions']['submit']['#submit'] as $key => $value) {
      if ($value == '::save' || $value == '::submitForm') {
        unset($form['actions']['submit']['#submit'][$key]);
      }
    }
  }

  // Load dsu_engage module settings.
  $config = \Drupal::config('dsu_engage.settings');
  $language = \Drupal::languageManager()->getCurrentLanguage()->getName();
  $market = strtoupper($config->get('dsu_engage_api_market'));
  $countryName = $form_state->getValue('country');
  $uploadedFiles = $form_state->getValue('attach_a_file_2mb_limit_');

  // Managing attachment.
  $attachedFiles = [];
  if ($uploadedFiles) {
    foreach ($uploadedFiles as $uploadedFile) {
      $fileLoaded = \Drupal::entityTypeManager()->getStorage('file')
        ->load($uploadedFile);
      $fileContents = file_get_contents($fileLoaded->getFileUri());
      $fileEncoded = base64_encode($fileContents);
      $attachedFiles[] = [
        'attachmentName' => $fileLoaded->getFilename(),
        'attachmentBody' => $fileEncoded,
      ];
    }
  }
  
  // Send data in dsu engage API.
  if (!$form_state->hasAnyErrors()) {
    $subRequest = '';
    switch ($form_state->getValue('what_would_you_like_to_contact_us_about_today_')) {
      case "Question":
        $requestType = "Question/Suggestion";
        $subRequest = $form_state->getValue('question_about');
        break;

      case "Complaint":
        $requestType = "Complaint";
        $subRequest = $form_state->getValue('complaint_about');
        break;

      case "Compliment":
        $requestType = "Compliment";
        $subRequest = '';
        break;
    }
	
	// Add country prefix code in contact number.
    $prefix = $form_state->getValue('country_code_field') ? '+' . $form_state->getValue('country_code_field') : "";
    $phone = $form_state->getValue('contact_number') ? $prefix . $form_state->getValue('contact_number') : "";

	// Prepare data for API.
    $data = [
      "brand" => $config->get('dsu_engage_api_brand'),
      "market" => $market,
      "country" => $countryName,
      "language" => $language,
      "consumerContactOrigin" => $config->get('dsu_engage_api_contact_origin'),
      "requestType" => $requestType,
      "firstName" => ucfirst($form_state->getValue('your_first_name')),
      "lastName" => ucfirst($form_state->getValue('your_last_name')),
      "email" => $form_state->getValue('email_me'),
      "street" => ($form_state->getValue('street')) ? $form_state->getValue('street') : NULL,
      "zipCode" => ($form_state->getValue('zipcode')) ? $form_state->getValue('zipcode') : NULL,
      "city" => ($form_state->getValue('city')) ? $form_state->getValue('city') : NULL,
      "state" => ($form_state->getValue('state')) ? $form_state->getValue('state') : NULL,
      "description" => $form_state->getValue('your_message'),
      "preferredChannel" => $form_state->getValue('preferred_channel') ? ucfirst($form_state->getValue('preferred_channel')) : 'Email',
      "phone" => $phone,
      "attachments" => $attachedFiles,
      "barCode" => ($form_state->getValue('barcode')) ? $form_state->getValue('barcode') : NULL,
      "batchCode" => ($form_state->getValue('batchcode')) ? $form_state->getValue('batchcode') : NULL,
      "productDescription" => ($form_state->getValue('product_description')) ? $form_state->getValue('product_description'): '',
      "JSONRequestId" => $form_state->getValue('form_build_id'),
      "subRequestType" => $subRequest,
    ];

    if ($form_state->getValue('what_would_you_like_to_contact_us_about_today_') == "complaint") {
      $data["bestBeforeDate"] = $form_state->getValue('bestBeforeDate') ? $form_state->getValue('bestBeforeDate') : NULL;
    }
	
	// Get token from API.
    $token = DsuEngageController::dsuEngageGetToken();

	// Check token value.
    if (!$token['access_token']) {
      \Drupal::messenger()->addMessage(t('The access token is wrong. Your request was not sent to our contact system.'), 'error');
      $form_state->setRebuild();
    }
	
    $options = [
      'method' => 'POST',
      'json' => $data,
      'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => 'Bearer ' . $token['access_token'],
      ],
    ];

	// Send data in engage API.
    $response = DsuEngageController::dsuEngageHttpRequest(
      $config->get('dsu_engage_api_endpoint_url'),
      $options
    );
	
    $responseOk = $response->getStatusCode() === 200;
    $responseData = Json::decode(Json::decode($response->getBody()));
	
	// Check API response.
    if ($responseData['status'] === 'failure') {
      \Drupal::messenger()->addMessage($responseData['ErrorMessage'], 'error');
      $form_state->setRebuild();
    }

	// Set message based on API response.
    if ($responseOk && $responseData['status'] !== 'failure') {
      // Confirmation message.
      \Drupal::messenger()->addMessage(t('Your ticket is created. Your contact number is: @ticket', ['@ticket' => $responseData['caseNumber']]));

    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Extend DSU engage setting form.
 */
function ln_contactus_block_form_dsu_engage_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::service('config.factory')->getEditable('dsu_engage.settings');
  $settingsForm['webform_submission'] = [
    '#type' => 'details',
    '#title' => t('Contact us Block Form'),
    '#description' => 'Send Contact Us webform data to Engage based on the following configurations.',
  ];
  $settingsForm['webform_submission']['dsu_engage_api_send_to_engage'] = [
    '#type' => 'checkbox',
    '#title' => t('Send to Engage'),
    '#description' => t('Keep this unchecked to store contact webform submissions locally instead of sending to Engage.'),
    '#default_value' => $config->get('dsu_engage_api_send_to_engage') ?? TRUE,
  ];

  $country_repository = \Drupal::service('address.country_repository');
  $countries_array = $country_repository->getList();
  $countries = array_combine($countries_array, $countries_array);
  unset($countries['-Select country-']);
  $settingsForm['webform_submission']['dsu_engage_api_exclusion_list'] = [
    '#type' => 'select',
    '#title' => t('Exclusion list'),
    '#description' => t('Select countries for which Contact Us submission data will be stored locally and not sent to Engage, even if the "Send to Engage" option is selected. By default, no countries are excluded.'),
    '#default_value' => $config->get('dsu_engage_api_exclusion_list'),
    '#options' => $countries_array,
    '#multiple' => TRUE,
  ];

  $settingsForm['webform_submission']['dsu_engage_api_country_select'] = [
    '#type' => 'select',
    '#title' => t('Locations options'),
    '#description' => t('Select the countries to show on the submission form (multi-select) if a subset is desired. By default, all countries will be shown in the form if none are selected'),
    '#default_value' => $config->get('dsu_engage_api_country_select'),
    '#options' => $countries_array,
    '#multiple' => TRUE,
  ];

  $settingsForm['webform_submission']['dsu_engage_api_business_email'] = [
    '#type' => 'email',
    '#title' => t('Business email address'),
    '#description' => t('Enter the email address that will receive user submission notifications (non-Engage submissions only)'),
    '#default_value' => $config->get('dsu_engage_api_business_email'),
  ];
  // Add field in Engage API tab.
  $form['engage_api'] += $settingsForm;
}
