ln_alkemics.settings:
  type: config_object
  mapping:
    ln_alkemics:
      type: mapping
      mapping:
        alkemics_api_endpoint_token_url:
          type: uri
          label: API Endpoint Token URL
        alkemics_api_endpoint_url:
          type: uri
          label: Products Endpoint URL
        alkemics_api_client_id:
          type: string
          label: API Client ID
        alkemics_api_client_secret:
          type: string
          label: API Client Secret
        alkemics_api_user_username:
          type: string
          label: API Username
        alkemics_api_user_password:
          type: string
          label: API Password
        alkemics_api_target_market_id:
          type: string
          lable: Target Market ID
        alkemics_api_target_brand_id:
          type: string
          label: Target Brand ID
        alkemics_api_product_search_endpoint:
          type: string
          label: Product Search Endpoint
        alkemics_api_target_market_keyword:
          type: string
          label: Product By Market Keyword
        alkemics_connect_interval:
          type: integer
          label: Interval to Sync Products
        alkemics_connect_isnew:
          type: integer
          label: Interval for Products marked as new
        alkemics_periodic_import_time_interval:
          type: boolean
          label: Schedule synchronization
        alkemics_periodic_import_enabled:
          type: boolean
          label: Enable periodic import
        alkemics_api_market_gtin:
          type: string
          label: GTIN
