<?php

/**
 * @file
 * Contains dsu_c_text.module.
 */

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_text_preprocess_paragraph(&$variables) {
  // Load the css file when the rendered element is a Text Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_text/general';
  if ($variables['paragraph']->getType() == 'c_text') {
    if (isset($variables['content']['field_background_image'])) {
      $ref_entities_classy_para = $variables['paragraph']->get('field_classy_paragraph_style')
        ->referencedEntities();
      if (!empty($ref_entities_classy_para)) {
        $ref_entity_classy_para = array_shift($ref_entities_classy_para);
        if (!empty($ref_entity_classy_para)) {
          $classy_paragraph = $ref_entity_classy_para->id();
          if ($classy_paragraph == 'dsu_classy_text_image_background') {
            if (isset($variables['content']['field_background_image']['#items'])) {
              $ref_entities = $variables['content']['field_background_image']['#items']->referencedEntities();
              $ref_entity = array_shift($ref_entities);
              $field_name = ($ref_entity->hasField('image'))
                ? 'image'
                : (($ref_entity->hasField('field_media_image')) ? 'field_media_image' : 'field_media_image');
              $fid = $ref_entity->get($field_name)
                       ->first()
                       ->getValue()['target_id'];
              $file = \Drupal\file\Entity\File::load($fid);
              $url = \Drupal\image\Entity\ImageStyle::load('text_background_image_1920x795_')
                ->buildUrl($file->getFileUri());
              $variables['field_background_image_img_url'] = $url;
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_theme.
 */
function dsu_c_text_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_text' => [
      'template'  => 'paragraph--c-text',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_ln_sample_content().
 */
function dsu_c_text_ln_sample_content() {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::service('module_handler');
  /** @var \Drupal\Core\Extension\Extension $module_object */
  $module_object = $module_handler->getModule(basename(__FILE__, '.module'));
  $module_name = $module_object->getName();

  $source = drupal_get_path('module', $module_name) . '/content';
  /** @var \Drupal\Core\File\FileSystemInterface $file_system */
  $file_system = \Drupal::service('file_system');
  $files = $file_system->scanDirectory($source, '/demo.*\.(yml)$/');
  $yaml_file_path = NULL;
  foreach ($files as $file) {
    $yaml_file_path[] = '/content/' . $file->filename;
  }

  return $yaml_file_path;
}