<?php

/**
 * @file
 */

use Drupal\field\FieldConfigInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements HOOK_preprocess_theme().
 */
function ln_c_newsletter_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_newsletter_signup_cta' => [
      'template'  => 'paragraph--c-newsletter-signup-cta',
      'base hook' => 'paragraphs',
    ],
    'webform__newsletter_email_collection' => [
      'base hook' => 'webform',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function ln_c_newsletter_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'c_newsletter_signup_cta') {
    $variables['#attached']['library'][] = 'ln_c_newsletter/ln_c_newsletter';
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add submit handler on contactus webform.
 */
function ln_c_newsletter_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strstr($form_id, 'webform_submission_newsletter_email_collection_')) {
	  $form['#attached']['library'][] = 'ln_c_newsletter/webform-styling';  
  }
}
