advanced_datalayer.advanced_datalayer_tag.brand:
  type: string
  label: 'Brand'
advanced_datalayer.advanced_datalayer_tag.business:
  type: string
  label: 'Business'
advanced_datalayer.advanced_datalayer_tag.businessUnit:
  type: string
  label: 'Business unit'
advanced_datalayer.advanced_datalayer_tag.conversionPageType:
  type: string
  label: 'Conversion page type'
advanced_datalayer.advanced_datalayer_tag.country:
  type: string
  label: 'Country'
advanced_datalayer.advanced_datalayer_tag.deviceType:
  type: string
  label: 'Device type'
advanced_datalayer.advanced_datalayer_tag.digiPiID:
  type: string
  label: 'digiPi ID'
advanced_datalayer.advanced_datalayer_tag.event:
  type: string
  label: 'Main tag event'
advanced_datalayer.advanced_datalayer_tag.gaClientID:
  type: string
  label: 'GA client ID'
advanced_datalayer.advanced_datalayer_tag.goLiveDate:
  type: string
  label: 'Go live date'
advanced_datalayer.advanced_datalayer_tag.language:
  type: string
  label: 'Language'
advanced_datalayer.advanced_datalayer_tag.pageCategory:
  type: string
  label: 'Page category'
advanced_datalayer.advanced_datalayer_tag.pageName:
  type: label
  label: 'Page Name'
advanced_datalayer.advanced_datalayer_tag.pageSection:
  type: string
  label: 'Page Section'
advanced_datalayer.advanced_datalayer_tag.pageSubsection:
  type: string
  label: 'Page Subsection'
advanced_datalayer.advanced_datalayer_tag.properties:
  type: string
  label: 'Properties'
advanced_datalayer.advanced_datalayer_tag.propertyStatus:
  type: string
  label: 'Property status'
advanced_datalayer.advanced_datalayer_tag.siteCategory:
  type: string
  label: 'Site Category'
advanced_datalayer.advanced_datalayer_tag.siteName:
  type: string
  label: 'Site name'
advanced_datalayer.advanced_datalayer_tag.siteType:
  type: string
  label: 'Site type'
advanced_datalayer.advanced_datalayer_tag.statusHttps:
  type: string
  label: 'Status Https'
advanced_datalayer.advanced_datalayer_tag.targetAudience:
  type: string
  label: 'Target audience'
advanced_datalayer.advanced_datalayer_tag.technology:
  type: string
  label: 'Technology'
advanced_datalayer.advanced_datalayer_tag.websiteUrl:
  type: label
  label: 'Website Url'
advanced_datalayer.advanced_datalayer_tag.zone:
  type: string
  label: 'Zone'
