<?php

/**
 * @file
 * Contains dsu_security_admin_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsu_security_admin_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsu_security_admin_module module.
    case 'help.page.dsu_security_admin_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Security module to enable/disable login page to the administration') . '</p>';
      return $output;

    default:
  }
}
