<?php

/**
 * @file
 * Contains newnestlegermany_components_accordion.module.
 */

use Drupal\paragraphs\Entity\Paragraph;
/**
 * Implements hook_theme().
 */
function dsu_c_accordion_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__accordion' => [
      'template' => 'paragraph--accordion',
      'base hook' => 'paragraph',
    ],
    'paragraph__accordion_item' => [
      'template' => 'paragraph--accordion-item',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dsu_c_accordion_preprocess_paragraph__accordion(&$variables) {
  $variables['#attached']['library'][] = 'dsu_c_accordion/accordion';
  $item_ids = [];
  foreach ($variables['paragraph']->get('field_accordion_item')->getValue() as $item) {
    $item_ids[] = $item['target_id'];
  }
  if (!empty($item_ids)) {
    $accordion_items = \Drupal::entityTypeManager()->getStorage('paragraph')->loadMultiple($item_ids);
    $items = '';
    if (!empty($accordion_items)) {
      $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      foreach ($accordion_items as $accordion_item) {
        if ($accordion_item->hasTranslation($language)) {
          $item_translation = $accordion_item->getTranslation($language);
          $question = $item_translation->get('field_c_title')->getString();
          $paragraph_id = '';
          if (!empty($item_translation->get('field_column_first')->first())) {
            $paragraph_id = $item_translation->get('field_column_first')->first()->getValue();
          }
          accordion_data_output($question, $paragraph_id, $items);
        }
      }
      $items = substr($items,0,-2);

      $js_data = '{
      "@context" : "https://schema.org",
      "@type" : "FAQPage",
      "mainEntity" : ['.$items.']
    }';
      $variables['#attached']['html_head'][] = [
        [
          '#type'       => 'html_tag',
          '#tag'        => 'script',
          '#attributes' => [
            'type'  => "application/ld+json",
          ],
          '#value'      => $js_data,
        ],
      ];
    }
  }

}

/**
 * Implements hook_ln_sample_content().
 */

function dsu_c_accordion_ln_sample_content() {
    /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
    $module_handler = \Drupal::service('module_handler');
    /** @var \Drupal\Core\Extension\Extension $module_object */
    $module_object = $module_handler->getModule(basename(__FILE__, '.module'));
    $module_name = $module_object->getName();

    $source = drupal_get_path('module', $module_name) . '/content';
    /** @var \Drupal\Core\File\FileSystemInterface $file_system */
    $file_system = \Drupal::service('file_system');
    $files = $file_system->scanDirectory($source, '/demo.*\.(yml)$/');
    $yaml_file_path = NULL;
    foreach ($files as $file) {
        $yaml_file_path[] = '/content/' . $file->filename;
    }

    return $yaml_file_path;
}

  /**
   * @param $question
   *  Accordion title.
   *
   * @param $paragraph
   *  Reference paragraph.
   *
   * @param $items
   *  Refernce varible.
   *
   */
function  accordion_data_output($question, $paragraph, &$items) {
  $ans_paragraph = Paragraph::load($paragraph['target_id']);
  if ($ans_paragraph->hasField('field_summary_text') && !empty($ans_paragraph->get('field_summary_text')
      ->getValue())) {
    // Remove html tag and \r\n from text.
    $answer = preg_replace('/\s\s+/', '', strip_tags($ans_paragraph->get('field_summary_text')
      ->first()->get('value')->getString()));

  }
  $items .= '{
    "@type" : "Question",
    "name" : "'.$question.'",
    "acceptedAnswer" : {
      "@type" : "Answer",
      "text" : "'.$answer.'"
      }
    }, ';
}