<?php

/**
 * @file
 * Hook implementations for dsu_c_block_component.module.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 * @param array $suggestions
 * @param array $variables
 */
function dsu_c_block_component_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content']) && $variables['elements']['content']['#block_content']->bundle() == 'component_block') {
    array_splice($suggestions, 1, 0, 'block__dsu_c_' . $variables['elements']['content']['#block_content']->bundle());
  }
}

/**
 * Implements HOOK_preprocess_theme().
 */
function dsu_c_block_component_theme($existing, $type, $theme, $path) {
  return [
    'block__dsu_c_component_block' => [
      'template'  => 'block--dsu-c-component-block',
      'base hook' => 'block',
    ],
  ];
}
